### ISSUE TITLE
Startup checks

### ISSUE THREAD

**Issue by brainfunked** [gluster/gadmin#13]
- [ ] Are we running as root? If yes, warn and exit.
- [ ] Is `$GADMIN_HOME` set and the corresponding work directory writable?
  - [ ] System-wide configuration: #5
  - [ ] Non-privileged user with no system-wide configuration: #6
- [ ] Is ansible installed? #7
- [ ] Are the necessary ansible roles installed? #7
- [ ] Does the host inventory exist? If yes, refresh it. #9
- [ ] If only one cluster has been defined, verify (#10) and select it (#12).
- [ ] If more than one cluster has been defined, ask the user (#11) to select one (#12).

**Comment by sac** [comment]
Ansible, and gluster-ansible can be added as dependencies. The checks are not necessary.
